export const EXERCISES = [
  'Abductor Machine',
  'Barbell Row',
  'Bench Press',
  'Bicep Curls (Cable)',
  'Bicep Curls (Dumbbells)',
  'Cable Crunches',
  'Calf Raises',
  'Chest Fly',
  'Deadlifts',
  'Dips',
  'Face Pulls',
  'Hamstring Curl (Lying)',
  'Hamstring Curl (Seated)',
  'Incline Dumbbell Curls',
  'Incline Dumbbell Press',
  'Lat Pulldown',
  'Lateral Raises',
  'Leg Press',
  'Leg Raises',
  'Lunges',
  'Overhead Press',
  'Planks',
  'Pull-Ups',
  'Push-Ups',
  'Quad Extension',
  'Romanian Deadlift',
  'Russian Twists',
  'Seated Row',
  'Skull Crushers',
  'Squats',
  'Triceps Pushdown',
];